### ISSUE TITLE
Custom Filter Bands( freqs_band) Issue with Fix

### ISSUE THREAD

**Issue by SulemanRasheed** [jesus-333/FBCSP-Python#6]
The default **_freqs_band_** argument choice FBCSP_4 is `np.linspace(4, 40, 10)` while I want to pass a custom one np.linspace(8, 32, 7) but your code gives a bug associated to this assertion (freqs_band == None)

**Your Code**
```
Frequencies band
         if(freqs_band == None): self.freqs = np.linspace(4, 40, 10)
         else: self.freqs =  freqs_band

```        

**My Fix**
```
        if isinstance(freqs_band, np.ndarray):
            self.freqs = freqs_band
        elif(freqs_band == None):
            self.freqs = np.linspace(4, 40, 10)
        else:
            raise ValueError('freqs_band must be a Numpy Array')
```

Btw your code is really helpful in my project and luckily I found it. Thanks for making it opensource

**Comment by jesus-333** [comment]
Thanks. I had update my code
